name: unofficial_conference_app_2020
description: Unofficial DroidKaigi App 2020
version: 1.0.0+1

module:
  androidX: true

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 
  intl_translation:
  http: ^0.12.0+4
  rxdart: ^0.22.1
  provider:
  collection:
  cupertino_icons:
  flutter_webview_plugin:
  firebase_core:
  cloud_firestore: ^0.13.0+1
  firebase_auth:
  cached_network_image:
  google_fonts:
  shared_preferences: ^0.5.6+1
  package_info: ^0.4.0+13
  flutter_timetable_view:

dependency_overrides:
 intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
